-- MySQL Script generated by MySQL Workbench
-- Sun Jan 18 21:14:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_brigadas_maracaibo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_brigadas_maracaibo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_brigadas_maracaibo` DEFAULT CHARACTER SET utf8 ;
USE `db_brigadas_maracaibo` ;

-- -----------------------------------------------------
-- Table `db_brigadas_maracaibo`.`Institucion_Educativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_brigadas_maracaibo`.`Institucion_Educativa` (
  `idInstitucion` INT NOT NULL AUTO_INCREMENT,
  `nombre_institucion` VARCHAR(45) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idInstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_brigadas_maracaibo`.`Brigada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_brigadas_maracaibo`.`Brigada` (
  `idBrigada` INT NOT NULL AUTO_INCREMENT,
  `nombre_brigada` VARCHAR(45) NOT NULL,
  `area_accion` VARCHAR(45) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL,
  `Institucion_Educativa_idInstitucion` INT NOT NULL,
  PRIMARY KEY (`idBrigada`),
  INDEX `fk_Brigada_Institucion_Educativa_idx` (`Institucion_Educativa_idInstitucion` ASC) VISIBLE,
  CONSTRAINT `fk_Brigada_Institucion_Educativa`
    FOREIGN KEY (`Institucion_Educativa_idInstitucion`)
    REFERENCES `db_brigadas_maracaibo`.`Institucion_Educativa` (`idInstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_brigadas_maracaibo`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_brigadas_maracaibo`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `Brigada_idBrigada` INT NOT NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Brigada1_idx` (`Brigada_idBrigada` ASC) VISIBLE,
  CONSTRAINT `fk_Actividad_Brigada1`
    FOREIGN KEY (`Brigada_idBrigada`)
    REFERENCES `db_brigadas_maracaibo`.`Brigada` (`idBrigada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_brigadas_maracaibo`.`Indicador_ambiental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_brigadas_maracaibo`.`Indicador_ambiental` (
  `idIndicador` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `tipo_indicador` VARCHAR(45) NOT NULL,
  `unidad` VARCHAR(5) NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`idIndicador`),
  INDEX `fk_Indicador_ambiental_Actividad1_idx` (`Actividad_idActividad` ASC) VISIBLE,
  CONSTRAINT `fk_Indicador_ambiental_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `db_brigadas_maracaibo`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_brigadas_maracaibo`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_brigadas_maracaibo`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `Brigada_idBrigada` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Brigada1_idx` (`Brigada_idBrigada` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Brigada1`
    FOREIGN KEY (`Brigada_idBrigada`)
    REFERENCES `db_brigadas_maracaibo`.`Brigada` (`idBrigada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_brigadas_maracaibo`.`Reporte_de_impacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_brigadas_maracaibo`.`Reporte_de_impacto` (
  `idReporte_impacto` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha_generacion` TIMESTAMP NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idReporte_impacto`),
  INDEX `fk_Reporte_de_impacto_Actividad1_idx` (`Actividad_idActividad` ASC) VISIBLE,
  INDEX `fk_Reporte_de_impacto_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_de_impacto_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `db_brigadas_maracaibo`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_de_impacto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `db_brigadas_maracaibo`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
